[package]
name = "crate_diesel_ormless_quickstart"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.3", features = ["postgres", "chrono"] }
dotenvy = "0.15"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
 